


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pg_net" WITH SCHEMA "extensions";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."notify_telegram_guestbook"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
declare
  payload jsonb;
begin
  payload := jsonb_build_object(
    'chat_id', '8632995313',
    'text', format('Nový vzkaz v Knize návštěv!%sOd: %s%sVzkaz: %s', E'\n', new.name, E'\n', new.message)
  );

  perform net.http_post(
    url := 'https://api.telegram.org/bot8919825940:AAFV-fivjwM0fo_SrLtcxG0c7E1lHEYTVBM/sendMessage',
    headers := '{"Content-Type": "application/json"}'::jsonb,
    body := payload
  );

  return new;
end;
$$;


ALTER FUNCTION "public"."notify_telegram_guestbook"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."notify_telegram_project_comment"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
declare
  payload jsonb;
begin
  payload := jsonb_build_object(
    'chat_id', '8632995313',
    'text', format('Nový komentář u PROJEKTU!%sProjekt: %s%sOd: %s%sKomentář: %s', E'\n', new.project_slug, E'\n', new.name, E'\n', new.comment)
  );

  perform net.http_post(
    url := 'https://api.telegram.org/bot8919825940:AAFV-fivjwM0fo_SrLtcxG0c7E1lHEYTVBM/sendMessage',
    headers := '{"Content-Type": "application/json"}'::jsonb,
    body := payload
  );

  return new;
end;
$$;


ALTER FUNCTION "public"."notify_telegram_project_comment"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."notify_telegram_recipe_comment"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
declare
  payload jsonb;
begin
  payload := jsonb_build_object(
    'chat_id', '8632995313',
    'text', format('Nový komentář u RECEPTU!%sRecept: %s%sOd: %s%sKomentář: %s', E'\n', new.recipe_slug, E'\n', new.name, E'\n', new.comment)
  );

  perform net.http_post(
    url := 'https://api.telegram.org/bot8919825940:AAFV-fivjwM0fo_SrLtcxG0c7E1lHEYTVBM/sendMessage',
    headers := '{"Content-Type": "application/json"}'::jsonb,
    body := payload
  );

  return new;
end;
$$;


ALTER FUNCTION "public"."notify_telegram_recipe_comment"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."guestbook" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "name" "text" NOT NULL,
    "message" "text" NOT NULL,
    "type" "text" DEFAULT 'prani'::"text" NOT NULL
);


ALTER TABLE "public"."guestbook" OWNER TO "postgres";


ALTER TABLE "public"."guestbook" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."guestbook_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."project_comments" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "project_slug" "text" NOT NULL,
    "name" "text" NOT NULL,
    "comment" "text" NOT NULL
);


ALTER TABLE "public"."project_comments" OWNER TO "postgres";


ALTER TABLE "public"."project_comments" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."project_comments_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."projects" (
    "slug" "text" NOT NULL,
    "title" "text" NOT NULL,
    "category" "text" NOT NULL,
    "shortDescription" "text" NOT NULL,
    "image" "text" NOT NULL,
    "imageAlt" "text" NOT NULL,
    "date" "text" NOT NULL,
    "featured" boolean DEFAULT false,
    "purpose" "text" NOT NULL,
    "description" "text" NOT NULL,
    "components" "jsonb" DEFAULT '[]'::"jsonb",
    "steps" "jsonb" DEFAULT '[]'::"jsonb",
    "notes" "text",
    "links" "jsonb" DEFAULT '[]'::"jsonb",
    "code" "text",
    "gallery" "jsonb" DEFAULT '[]'::"jsonb",
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL
);


ALTER TABLE "public"."projects" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."recipe_comments" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "recipe_slug" "text" NOT NULL,
    "name" "text" NOT NULL,
    "comment" "text" NOT NULL
);


ALTER TABLE "public"."recipe_comments" OWNER TO "postgres";


ALTER TABLE "public"."recipe_comments" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."recipe_comments_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."recipes" (
    "slug" "text" NOT NULL,
    "title" "text" NOT NULL,
    "shortDescription" "text" NOT NULL,
    "image" "text" NOT NULL,
    "imageAlt" "text" NOT NULL,
    "date" "text" NOT NULL,
    "intro" "text" NOT NULL,
    "ingredients" "jsonb" DEFAULT '[]'::"jsonb" NOT NULL,
    "steps" "jsonb" DEFAULT '[]'::"jsonb" NOT NULL,
    "notes" "text",
    "servings" "text",
    "prepTime" "text",
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "description" "text"
);


ALTER TABLE "public"."recipes" OWNER TO "postgres";


ALTER TABLE ONLY "public"."guestbook"
    ADD CONSTRAINT "guestbook_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."project_comments"
    ADD CONSTRAINT "project_comments_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."projects"
    ADD CONSTRAINT "projects_pkey" PRIMARY KEY ("slug");



ALTER TABLE ONLY "public"."recipe_comments"
    ADD CONSTRAINT "recipe_comments_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."recipes"
    ADD CONSTRAINT "recipes_pkey" PRIMARY KEY ("slug");



CREATE OR REPLACE TRIGGER "on_guestbook_insert" AFTER INSERT ON "public"."guestbook" FOR EACH ROW EXECUTE FUNCTION "public"."notify_telegram_guestbook"();



CREATE OR REPLACE TRIGGER "on_project_comment_insert" AFTER INSERT ON "public"."project_comments" FOR EACH ROW EXECUTE FUNCTION "public"."notify_telegram_project_comment"();



CREATE OR REPLACE TRIGGER "on_recipe_comment_insert" AFTER INSERT ON "public"."recipe_comments" FOR EACH ROW EXECUTE FUNCTION "public"."notify_telegram_recipe_comment"();



CREATE POLICY "Admini mohou upravovat recepty" ON "public"."recipes" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Enable delete for authenticated users only" ON "public"."recipes" FOR DELETE TO "authenticated" USING (true);



CREATE POLICY "Enable insert for authenticated users only" ON "public"."recipes" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Enable update for authenticated users only" ON "public"."recipes" FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Povolit cteni komentaru receptu vsem" ON "public"."recipe_comments" FOR SELECT USING (true);



CREATE POLICY "Povolit cteni komentaru vsem" ON "public"."project_comments" FOR SELECT USING (true);



CREATE POLICY "Povolit mazani pouze adminovi" ON "public"."guestbook" FOR DELETE TO "authenticated" USING (true);



CREATE POLICY "Povolit mazani projektu pouze adminovi" ON "public"."projects" FOR DELETE TO "authenticated" USING (true);



CREATE POLICY "Povolit upravu projektu pouze adminovi" ON "public"."projects" FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Povolit verejne cteni projektu" ON "public"."projects" FOR SELECT TO "authenticated", "anon" USING (true);



CREATE POLICY "Povolit verejne cteni vzkazu" ON "public"."guestbook" FOR SELECT TO "authenticated", "anon" USING (true);



CREATE POLICY "Povolit verejne vkladani vzkazu" ON "public"."guestbook" FOR INSERT TO "authenticated", "anon" WITH CHECK (true);



CREATE POLICY "Povolit veřejné přidávání vzkazů" ON "public"."guestbook" FOR INSERT TO "anon" WITH CHECK (true);



CREATE POLICY "Povolit veřejné čtení vzkazů" ON "public"."guestbook" FOR SELECT TO "anon" USING (true);



CREATE POLICY "Povolit vkladani komentaru receptu vsem" ON "public"."recipe_comments" FOR INSERT WITH CHECK (true);



CREATE POLICY "Povolit vkladani komentaru vsem" ON "public"."project_comments" FOR INSERT WITH CHECK (true);



CREATE POLICY "Povolit vkladani projektu pouze adminovi" ON "public"."projects" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Public recipes are viewable by everyone" ON "public"."recipes" FOR SELECT USING (true);



CREATE POLICY "Veřejné čtení receptů" ON "public"."recipes" FOR SELECT USING (true);



ALTER TABLE "public"."guestbook" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."project_comments" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."projects" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."recipe_comments" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."recipes" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";





GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";






















































































































































GRANT ALL ON FUNCTION "public"."notify_telegram_guestbook"() TO "anon";
GRANT ALL ON FUNCTION "public"."notify_telegram_guestbook"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."notify_telegram_guestbook"() TO "service_role";



GRANT ALL ON FUNCTION "public"."notify_telegram_project_comment"() TO "anon";
GRANT ALL ON FUNCTION "public"."notify_telegram_project_comment"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."notify_telegram_project_comment"() TO "service_role";



GRANT ALL ON FUNCTION "public"."notify_telegram_recipe_comment"() TO "anon";
GRANT ALL ON FUNCTION "public"."notify_telegram_recipe_comment"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."notify_telegram_recipe_comment"() TO "service_role";


















GRANT ALL ON TABLE "public"."guestbook" TO "anon";
GRANT ALL ON TABLE "public"."guestbook" TO "authenticated";
GRANT ALL ON TABLE "public"."guestbook" TO "service_role";



GRANT ALL ON SEQUENCE "public"."guestbook_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."guestbook_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."guestbook_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."project_comments" TO "anon";
GRANT ALL ON TABLE "public"."project_comments" TO "authenticated";
GRANT ALL ON TABLE "public"."project_comments" TO "service_role";



GRANT ALL ON SEQUENCE "public"."project_comments_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."project_comments_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."project_comments_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."projects" TO "anon";
GRANT ALL ON TABLE "public"."projects" TO "authenticated";
GRANT ALL ON TABLE "public"."projects" TO "service_role";



GRANT ALL ON TABLE "public"."recipe_comments" TO "anon";
GRANT ALL ON TABLE "public"."recipe_comments" TO "authenticated";
GRANT ALL ON TABLE "public"."recipe_comments" TO "service_role";



GRANT ALL ON SEQUENCE "public"."recipe_comments_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."recipe_comments_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."recipe_comments_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."recipes" TO "anon";
GRANT ALL ON TABLE "public"."recipes" TO "authenticated";
GRANT ALL ON TABLE "public"."recipes" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































